(function(){
      "use strict";
      const REQUESTS_KEY="tramipago_requests_v1";
      const cardMeta={"antecedentes-penales":{title:"Antecedentes Penales",subtitle:"Certificado Online"},"constancias-anses":{title:"ANSES",subtitle:"CODEM + Negativa"},"arca-monotributo":{title:"ARCA",subtitle:"Monotributo / VEP"},"informe-vehicular":{title:"Informe Vehicular",subtitle:"Dominio + Infracciones + Patentes"},"partidas-pba":{title:"Partidas y Certificados",subtitle:"Gestión online"},"arba-inmobiliario":{title:"ARBA / Inmobiliario",subtitle:"Deuda + Plancheta"},"asistencia-digital":{title:"Asistencia Digital",subtitle:"ANSES / ARCA / Mi Argentina"}};
      function normalize(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();}
      function readRequests(){try{return JSON.parse(localStorage.getItem(REQUESTS_KEY)||"[]");}catch(_){return[];}}
      function getRequestByCode(code){const normalized=String(code||"").trim().toUpperCase();return readRequests().find(item=>String(item.code||"").toUpperCase()===normalized)||null;}
      function dateParts(value){const date=value?new Date(value):new Date();return{date:new Intl.DateTimeFormat("es-AR",{dateStyle:"medium"}).format(date),time:new Intl.DateTimeFormat("es-AR",{timeStyle:"short"}).format(date)};}
      function escapeText(value){return String(value==null?"":value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
      function updateView(){document.body.dataset.view=(!location.hash||location.hash==="#/")?"home":"inner";}
      function decorateCard(card){if(card.dataset.visualReady==="true")return;const id=card.dataset.serviceId||card.dataset.familyId||"";const meta=cardMeta[id]||{title:card.getAttribute("aria-label")||"Trámite",subtitle:"Gestión online"};const media=card.querySelector(".home-tile-media");if(media)media.classList.add("card-photo");const info=document.createElement("span");info.className="catalog-card-info";info.innerHTML='<span class="catalog-card-title"></span><span class="catalog-card-subtitle"></span>';info.querySelector(".catalog-card-title").textContent=meta.title;info.querySelector(".catalog-card-subtitle").textContent=meta.subtitle;card.appendChild(info);if(meta.badge||card.disabled){const badge=document.createElement("span");badge.className="catalog-card-badge";badge.textContent=meta.badge||"Próximamente";card.appendChild(badge);}card.dataset.search=normalize(meta.title+" "+meta.subtitle);card.dataset.visualReady="true";}
      function buildCatalogSections(){const catalog=document.querySelector(".home-catalog .container");if(catalog)catalog.querySelectorAll(".home-tile").forEach(decorateCard);}
      function removeRedundantButtons(){document.querySelectorAll('.process-top [data-action="back-home"], .ineligible-panel [data-action="back-home"], .family-page .family-back[data-action="back-home"]').forEach(button=>button.remove());}
      function normalizeButtonLabels(){
        const replacements={"Crear solicitud":"Siguiente","Guardar y continuar":"Siguiente","Guardar cambios":"Guardá cambios","Volver":"Atrás","Consultar":"Consultá estado","Consultar estado":"Consultá estado","Revisar datos":"Modificar datos","Volver a datos":"Modificar datos","Informá pago":"Informar pago","Revisar requisitos":"Revisá requisitos","Copiar código":"Copiá código","Enviar corrección":"Enviá corrección","Corregir información":"Corregí información","Continuar con el pago":"Continuá con el pago","Descargar resultado":"Descargá resultado","Elegir trámite":"Elegí trámite","Ver mi trámite":"Ver estado"};
        document.querySelectorAll(".button").forEach(function(button){const label=button.textContent.trim();const next=replacements[label];if(next&&next!==label)button.textContent=next;});
      }
      function enhanceConfirmation(){const panel=document.querySelector(".confirmation");if(!panel||panel.dataset.detailsReady==="true")return;const codeNode=panel.querySelector(".request-code"),code=codeNode?codeNode.textContent.trim():"",request=getRequestByCode(code);if(!request)return;const timestamp=dateParts(request.updatedAt||request.createdAt),status=request.status==="payment_review"?"Pago en revisión":String(request.status||"Pendiente");const intro=panel.querySelector("h2 + p");if(intro)intro.textContent="Recibimos tu comprobante. Guardá estos datos para consultar el estado.";const summary=document.createElement("div");summary.className="confirmation-summary";summary.innerHTML='<div class="confirmation-summary-item"><small>Servicio TramiPago</small><strong>'+escapeText(request.serviceName)+'</strong></div><div class="confirmation-summary-item"><small>Estado</small><strong>'+escapeText(status)+'</strong></div><div class="confirmation-summary-item"><small>Fecha y hora</small><strong>'+escapeText(timestamp.date)+' · '+escapeText(timestamp.time)+'</strong></div>';const oldServiceStatus=codeNode.nextElementSibling;if(oldServiceStatus&&oldServiceStatus.tagName==="P")oldServiceStatus.remove();codeNode.insertAdjacentElement("afterend",summary);const actions=panel.querySelector(".confirmation-actions");if(actions){const trackingButton=actions.querySelector('[data-action="track-request"]');if(trackingButton)trackingButton.textContent="Ver estado";const copyButton=actions.querySelector('[data-action="copy-code"]');if(copyButton)copyButton.textContent="Copiá código";}panel.dataset.detailsReady="true";}
      function enhanceFinalizedTracking(){const result=document.querySelector(".tracking-result");if(!result||result.dataset.finalReady==="true")return;const badge=result.querySelector(".status-badge");if(!badge||normalize(badge.textContent)!=="finalizado")return;const codeNode=result.querySelector(".eyebrow"),code=codeNode?codeNode.textContent.trim():"",request=getRequestByCode(code);if(!request)return;const finished=dateParts(request.updatedAt||request.createdAt);const box=document.createElement("div");box.className="finalization-box";box.innerHTML='<h3>Trámite finalizado</h3><p>La gestión terminó. Conservá este código como referencia y revisá el resultado o la indicación de entrega.</p><div class="finalization-summary"><div class="finalization-summary-item"><small>Código</small><strong>'+escapeText(request.code)+'</strong></div><div class="finalization-summary-item"><small>Servicio</small><strong>'+escapeText(request.serviceName)+'</strong></div><div class="finalization-summary-item"><small>Fecha de finalización</small><strong>'+escapeText(finished.date)+'</strong></div><div class="finalization-summary-item"><small>Hora</small><strong>'+escapeText(finished.time)+'</strong></div><div class="finalization-summary-item"><small>Estado</small><strong>Finalizado</strong></div></div>';const statusHeader=result.querySelector(".status-header");if(statusHeader)statusHeader.insertAdjacentElement("afterend",box);result.dataset.finalReady="true";}
      function enhanceHome(){buildCatalogSections();}
      function enhanceInterface(){updateView();enhanceHome();removeRedundantButtons();normalizeButtonLabels();enhanceConfirmation();enhanceFinalizedTracking();}
      window.addEventListener("hashchange",()=>window.setTimeout(enhanceInterface,0));
      const app=document.getElementById("app");let uiQueued=false;function queueUi(){if(uiQueued)return;uiQueued=true;window.requestAnimationFrame(()=>{uiQueued=false;enhanceInterface();});}
      if(app)new MutationObserver(queueUi).observe(app,{childList:true,subtree:true});
      enhanceInterface();
    })();
