// Integración DOM simulada, sin mensajes reales, registros ni pagos.
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>readFileSync(resolve(root,p),'utf8');
const js=read('legal-landing-20260917.js'),css=read('legal-landing-20260917.css'),refresh=read('legal-design-refresh-20260917.css');
const search=read('catalog-search.js'),promos=read('promos.js'),header=read('header-fijo-20260917.js'),services=read('services.js');
assert.ok(search.includes('legal-landing-20260917.js'),'Módulo de abogado integrado');
assert.ok(promos.includes('href:"#/familia/atencion-abogado"'),'Publicidad conduce a consulta');
assert.ok(header.includes('const legalHref=\'#/familia/atencion-abogado\''),'Oblea conduce a consulta');
assert.ok(services.includes('whatsappNumber: "5491167083232"'),'WhatsApp configurado');
assert.ok(existsSync(resolve(root,'assets','promo-abogado-20260916.webp')),'Imagen de promoción existente');
assert.ok(css.includes('@media(max-width:980px)')&&css.includes('@media(max-width:620px)'),'Diseño adaptable');
assert.ok(refresh.includes('radial-gradient')&&refresh.includes('.header-slogan'),'Nuevo fondo luminoso y lema centrado');
assert.ok(!/1125013650|abogadosart\.com\.ar|consulta gratuita|honorarios a resultado exitoso/i.test(js),'Sin promesas ni datos de terceros');
const buttons=['art','accidentes','sucesiones','laboral'].map(id=>({dataset:{legalTopic:id},attributes:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(_ev,fn){this.click=fn;},closest(){return {classList:{toggle(){}}};}}));
let html='',hashHandler=null;const styles=[];const opened=[];
const form={elements:{fullName:{value:''},phone:{value:''},query:{value:''}},addEventListener(_name,fn){this.submit=fn;}};
const node={querySelectorAll:()=>buttons,querySelector(sel){return sel==='#legal-whatsapp-form'?form:null;}};
const shell={set innerHTML(value){html=value;},querySelector(sel){return sel==='#legal-consultation'?node:null;}};
const page={classList:{active:false,contains(){return this.active;},add(){this.active=true;}},querySelector:()=>shell};
const app={};
const document={readyState:'complete',head:{appendChild(el){styles.push(el);}},getElementById(id){return id==='app'?app:styles.find(el=>el.id===id)||null;},createElement(){return {};},querySelector(sel){return sel==='#app .family-page'?page:null;},addEventListener(){}};
const window={TRAMI_FAMILIES:[{id:'atencion-abogado'}],TRAMI_CONFIG:{whatsappNumber:'5491167083232'},open(url){opened.push(url);},addEventListener(_name,fn){hashHandler=fn;},alert(){throw Error('WhatsApp no debería faltar');}};
const location={hash:'#/familia/atencion-abogado'};
class Observer{observe(){}}
runInNewContext(js,{document,window,location,MutationObserver:Observer,requestAnimationFrame(fn){fn();},encodeURIComponent});
assert.ok(page.classList.active,'Se montó formulario legal');
assert.ok(html.includes('Dr. Francisco Liberatore')&&html.includes('Especialista en reclamos de ART'),'Identidad del servicio');
assert.equal((html.match(/data-legal-topic=/g)||[]).length,4,'Cuatro temas');
assert.ok(html.includes('Nombre y apellido')&&html.includes('Teléfono')&&html.includes('Consulta breve'),'Tres campos');
assert.ok(html.includes('Iniciar consulta'),'Botón final');
assert.ok(!html.includes('required'),'Campos opcionales');
assert.ok(!html.includes('El botón abre WhatsApp con tu mensaje preparado.'),'Texto redundante eliminado');
assert.ok(styles.some(style=>style.href.includes('legal-landing-20260917.css')),'CSS principal integrado');
assert.ok(styles.some(style=>style.href.includes('legal-design-refresh-20260917.css')),'Nuevo CSS visual integrado');
let prevented=0;const submit=()=>form.submit({preventDefault(){prevented++;},currentTarget:form});
submit();assert.equal(prevented,1,'Sin recarga');
assert.ok(opened.at(-1).startsWith('https://wa.me/5491167083232?text='),'WhatsApp del proyecto');
assert.ok(decodeURIComponent(opened.at(-1)).includes('Quisiera comunicarme para contar mi caso.'),'Se puede iniciar sin completar nada');
buttons[1].click();assert.equal(buttons[1].attributes['aria-pressed'],'true','Tema seleccionado');
assert.equal(buttons[0].attributes['aria-pressed'],'false','Un solo tema');
form.elements.fullName.value='Ana Pérez';form.elements.phone.value='11 5555 4444';form.elements.query.value='Choque en la calle';submit();
const message=decodeURIComponent(opened.at(-1));
for(const text of ['Tema: Accidentes','Nombre y apellido: Ana Pérez','Teléfono de contacto: 11 5555 4444','Consulta: Choque en la calle'])assert.ok(message.includes(text),'Mensaje incluye '+text);
buttons[1].click();assert.equal(buttons[1].attributes['aria-pressed'],'false','Deselección habilitada');
hashHandler();assert.ok(page.classList.active,'No duplica formulario');
console.log('PASS: consulta legal, estilos nuevos, temas únicos opcionales y WhatsApp con datos completos.');
console.log('Límite: simulación; el usuario debe pulsar Enviar en WhatsApp y verificar visualmente la publicación.');
