// Integración DOM simulada. No envía mensajes, no crea solicitudes y no cobra.
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>readFileSync(resolve(root,p),'utf8');
const js=read('legal-landing-20260917.js');
const css=read('legal-landing-20260917.css');
const search=read('catalog-search.js');
const promos=read('promos.js');
const header=read('header-fijo-20260917.js');
const services=read('services.js');
assert.ok(search.includes('import("./legal-landing-20260917.js'),'Módulo integrado en el sitio');
assert.ok(promos.includes('href:"#/familia/atencion-abogado"'),'Promoción del carrusel a la misma ruta');
assert.ok(header.includes('const legalHref="#/familia/atencion-abogado"'),'Aviso fijo a la misma ruta');
assert.ok(services.includes('whatsappNumber: "5491167083232"'),'Número del sitio configurado');
assert.ok(existsSync(resolve(root,'assets','promo-abogado-20260916.webp')),'Imagen existente de promoción');
assert.ok(css.includes('@media(max-width:980px)')&&css.includes('@media(max-width:620px)'),'Diseño adaptable');
assert.ok(!/1125013650|abogadosart\.com\.ar|consulta gratuita|honorarios a resultado exitoso/i.test(js),'No reutiliza datos/promesas de terceros');
const buttons=['art','accidentes','sucesiones','laboral'].map(id=>({dataset:{legalTopic:id},attributes:{},setAttribute(k,v){this.attributes[k]=v;},addEventListener(_ev,fn){this.click=fn;},closest(){return {classList:{toggle(){}}};}}));
let html='',style=null,hashHandler=null,opened=[];
const form={elements:{fullName:{value:''},phone:{value:''},query:{value:''}},addEventListener(_name,fn){this.submit=fn;}};
const node={querySelectorAll:()=>buttons,querySelector(sel){return sel==='#legal-whatsapp-form'?form:null;}};
const shell={set innerHTML(value){html=value;},querySelector(sel){return sel==='#legal-consultation'?node:null;}};
const page={classList:{active:false,contains(){return this.active;},add(){this.active=true;}},querySelector:()=>shell};
const app={};
const document={readyState:'complete',head:{appendChild(el){style=el;}},getElementById(id){return id==='app'?app:id==='tramipago-legal-landing-style'?style:null;},createElement(){return {};},querySelector(sel){return sel==='#app .family-page'?page:null;},addEventListener(){}};
const window={TRAMI_FAMILIES:[{id:'atencion-abogado'}],TRAMI_CONFIG:{whatsappNumber:'5491167083232'},open(url){opened.push(url);},addEventListener(_name,fn){hashHandler=fn;},alert(){throw Error('No debería faltar WhatsApp');}};
const location={hash:'#/familia/atencion-abogado'};
class Observer{observe(){}}
runInNewContext(js,{document,window,location,MutationObserver:Observer,requestAnimationFrame(fn){fn();},encodeURIComponent});
assert.ok(page.classList.active,'Nueva sección montada');
assert.ok(html.includes('Dr. Francisco Liberatore')&&html.includes('Especialista en reclamos de ART'),'Identidad y especialidad');
assert.equal((html.match(/data-legal-topic=/g)||[]).length,4,'Cuatro temas seleccionables');
assert.ok(html.includes('Nombre y apellido')&&html.includes('Teléfono')&&html.includes('Consulta breve'),'Tres campos');
assert.ok(html.includes('Iniciar consulta'),'Acción final correcta');
assert.ok(!html.includes('required'),'Ningún campo obligatorio');
assert.ok(style.href.includes('legal-landing-20260917.css'),'Estilo dedicado');
let prevented=0;
const submit=()=>form.submit({preventDefault(){prevented++;},currentTarget:form});
submit();
assert.equal(prevented,1,'Envío interceptado sin recarga');
assert.ok(opened.at(-1).startsWith('https://wa.me/5491167083232?text='),'WhatsApp de TramiPago');
assert.ok(decodeURIComponent(opened.at(-1)).includes('Quisiera comunicarme para contar mi caso.'),'Permite mensaje vacío sin tema');
buttons[1].click();
assert.equal(buttons[1].attributes['aria-pressed'],'true','Tema seleccionado');
assert.equal(buttons[0].attributes['aria-pressed'],'false','Selección única');
form.elements.fullName.value='Ana Pérez';form.elements.phone.value='11 5555 4444';form.elements.query.value='Choque en la calle';
submit();
const message=decodeURIComponent(opened.at(-1));
for(const part of ['Tema: Accidentes','Nombre y apellido: Ana Pérez','Teléfono de contacto: 11 5555 4444','Consulta: Choque en la calle'])assert.ok(message.includes(part),'Mensaje incluye: '+part);
buttons[1].click();assert.equal(buttons[1].attributes['aria-pressed'],'false','Permite deseleccionar');
hashHandler();assert.ok(page.classList.active,'No duplica el formulario');
console.log('PASS: cuatro temas opcionales, selección única reversible, datos opcionales, WhatsApp correcto, texto completo y no pago.');
console.log('NOTA: prueba simulada; WhatsApp requiere que la persona confirme el envío en su aplicación.');
