import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const promos=read('promos.js'),search=read('catalog-search.js'),catalog=read('tramites.html'),page=read('municipales.html'),styles=read('site.css');
// Auditoría estática: no suplanta verificaciones con datos reales de contribuyentes.
assert.match(promos,/promo-municipal-20260911\.webp[^\n]*href:["']municipales\.html["']/,'Anuncio municipal conduce a Municipales');
assert.match(promos,/function ensureMunicipalEntry\(/,'Entrada municipal definida');
assert.match(promos,/ensureMunicipalEntry\(\);/,'Entrada municipal montada');
assert.match(promos,/link\.href=["']municipales\.html#elegir-municipio["']/,'Entrada municipal vinculada al selector');
assert.match(promos,/<b>Seleccioná tu municipio<\/b>/,'Botón municipal con rótulo solicitado');
assert.match(search,/title:["']Trámites municipales: San Miguel y José C\. Paz["']/,'Municipales indexados en buscador');
assert.match(search,/href:["']municipales\.html["']/,'Buscador conduce a Municipales');
assert.match(catalog,/<h2>Trámites municipales — San Miguel y José C\. Paz<\/h2>/,'Municipales en catálogo');
assert.match(catalog,/href="municipales\.html"/,'Catálogo municipal vinculado');
assert.match(catalog,/href="index\.html#\/familia\/legalizaciones-apostillas"/,'Legalizaciones en catálogo');
assert.match(catalog,/href="index\.html#\/familia\/atencion-abogado"/,'Abogados en catálogo');
assert.match(page,/id="elegir-municipio"/,'Formulario selector visible');
assert.match(page,/name="municipio" value="jose-paz"/,'Opción José C. Paz');
assert.match(page,/name="municipio" value="san-miguel"/,'Opción San Miguel');
assert.match(page,/id="san-miguel"/,'San Miguel');
assert.match(page,/id="jose-paz"/,'José C. Paz');
assert.doesNotMatch(page,/La posibilidad de completar el trámite ante el organismo sin presencialidad/,'Sin párrafo redundante en José C. Paz');
assert.match(page,/No ofrecemos multas, infracciones ni trámites ante el Juzgado de Faltas/,'Exclusión de multas en José C. Paz');
assert.match(page,/No gestionamos multas, infracciones ni actuaciones ante el Juzgado de Faltas/,'Exclusión de multas en San Miguel');
assert.doesNotMatch(page,/Consulta y pago de tasas, multas y boletas/,'Sin promesa anterior de multas y tasas');
assert.match(styles,/f3de14_b18f1125127b4cc0a399602aa63de1b2~mv2\.png/,'Imagen usada por la tarjeta municipal');
assert.match(styles,/home-municipal-entry>b:hover/,'Texto del botón cambia al pasar el cursor');
assert.ok(fs.existsSync(new URL('../assets/logo-tramipago.webp',import.meta.url)),'Logo');
assert.ok(fs.existsSync(new URL('../assets/promo-municipal-20260911.webp',import.meta.url)),'Imagen municipal del carrusel');
assert.doesNotMatch(styles,/municipal-20260918\.avif/,'Sin recurso municipal obsoleto en CSS');
assert.equal((page.match(/class="municipal-consult-form"/g)||[]).length,2,'Un formulario por municipio');
assert.equal((page.match(/class="action primary municipal-send"/g)||[]).length,2,'Un botón Enviar consulta por municipio');
assert.match(page,/data-municipio="San Miguel"/,'Consulta identifica San Miguel');
assert.match(page,/data-municipio="José C. Paz"/,'Consulta identifica José C. Paz');
for(const campo of ['nombre','telefono','tramite']) assert.equal((page.match(new RegExp('name="'+campo+'"','g'))||[]).length,2,'Campo '+campo+' para ambos municipios');
assert.match(page,/wa\.me\/5491167083232\?text=/,'Envío a WhatsApp existente');
assert.match(page,/encodeURIComponent\(mensaje\)/,'Datos del formulario codificados en el mensaje');
assert.doesNotMatch(page,/Consultar disponibilidad por WhatsApp|Abrir portal oficial de pagos ↗|Abrir sitio oficial del municipio ↗/,'Sin botones anteriores');
assert.match(page,/municipal-consult-form \.municipal-send:hover/,'Hover del botón nuevo');
console.log('PASS: oferta acotada, modalidad no confirmada, exclusión de faltas, selector, enlaces y catálogo.');
console.log('Límite: revisión estática; no prueba en navegador, operaciones reales ni pagos.');
